#!/usr/bin/env python3
"""Fetch today's Resmi Gazete, summarize it in Turkish, and email the digest.

Pipeline:
  1. Download the daily archive page from resmigazete.gov.tr.
  2. Parse it into {category: [ {title, url}, ... ]} using a heading-then-links
     heuristic (the site's markup isn't guaranteed to have stable CSS classes,
     so this avoids depending on exact selectors).
  3. Ask Claude to turn the raw item list into a short, well-organized Turkish
     HTML email (highlights first, then grouped by category).
  4. Send the email via the Resend API.

Environment variables:
  TO_EMAIL            required  recipient address
  FROM_EMAIL          required  verified sender address (Resend)
  RESEND_API_KEY       required
  ANTHROPIC_API_KEY    required
  GAZETTE_DATE          optional  override date as YYYY-MM-DD (default: today, Europe/Istanbul)
  ANTHROPIC_MODEL       optional  default: claude-sonnet-5
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from urllib.parse import urljoin
from zoneinfo import ZoneInfo

import requests
from bs4 import BeautifulSoup

GAZETTE_BASE = "https://www.resmigazete.gov.tr"
HEADING_TAGS = {"h1", "h2", "h3", "h4", "h5", "h6"}
SKIP_HREF_PREFIXES = ("#", "javascript:", "mailto:", "tel:")
USER_AGENT = (
    "Mozilla/5.0 (compatible; ResmiGazeteDigestBot/1.0; "
    "+https://github.com/erhanere/HR-Report)"
)


@dataclass
class GazetteItem:
    title: str
    url: str


@dataclass
class GazetteDay:
    date: str
    source_url: str
    categories: dict[str, list[GazetteItem]] = field(default_factory=dict)

    @property
    def item_count(self) -> int:
        return sum(len(items) for items in self.categories.values())


def gazette_url_for(date: datetime) -> str:
    return f"{GAZETTE_BASE}/eskiler/{date:%Y}/{date:%m}/{date:%Y%m%d}.htm"


def fetch_page(url: str) -> requests.Response:
    return requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=30)


def _looks_like_heading(tag) -> bool:
    """Heuristic for section headers that aren't real <h1>-<h6> tags.

    Resmi Gazete section titles ("YÜRÜTME VE İDARE BÖLÜMÜ", "İLAN BÖLÜMÜ", ...)
    are short, upper-case, Turkish lines rendered as bold text rather than
    semantic headings.
    """
    if tag.name not in {"p", "div", "span", "strong", "b"}:
        return False
    if tag.find("a") is not None:
        return False
    text = tag.get_text(strip=True)
    if not text or text.upper() != text:
        return False
    if not (5 <= len(text) <= 100):
        return False
    return True


def parse_gazette(html: str, source_url: str, date_str: str) -> GazetteDay:
    soup = BeautifulSoup(html, "html.parser")
    day = GazetteDay(date=date_str, source_url=source_url)

    current_category = "Genel"
    seen_urls: set[str] = set()

    for tag in soup.find_all(True):
        if tag.name in HEADING_TAGS or _looks_like_heading(tag):
            text = tag.get_text(strip=True)
            if text:
                current_category = text
            continue

        if tag.name != "a":
            continue

        href = tag.get("href")
        text = tag.get_text(strip=True)
        if not href or not text or len(text) < 4:
            continue
        if href.startswith(SKIP_HREF_PREFIXES):
            continue

        absolute_url = urljoin(source_url, href)
        if absolute_url in seen_urls:
            continue
        seen_urls.add(absolute_url)

        day.categories.setdefault(current_category, []).append(
            GazetteItem(title=text, url=absolute_url)
        )

    return day


def build_email_html(day: GazetteDay, model: str) -> tuple[str, str]:
    """Return (subject, html_body) generated by Claude."""
    import anthropic

    client = anthropic.Anthropic()

    if day.item_count == 0:
        payload = "Bugün için Resmi Gazete'de ayrıştırılabilen bir madde bulunamadı."
    else:
        lines = []
        for category, items in day.categories.items():
            lines.append(f"## {category}")
            for item in items:
                lines.append(f"- {item.title} ({item.url})")
        payload = "\n".join(lines)

    prompt = f"""Aşağıda {day.date} tarihli Resmi Gazete'nin ham başlık listesi var \
(kategori başlıkları ## ile işaretli, her satır bir ilan/karar/yönetmelik başlığı ve linki).

Bu listeden, bir HR/yönetici için hazırlanmış kısa ve öz bir e-posta bülteni HTML gövdesi \
oluştur. Kurallar:
- Sade, responsive, inline-CSS kullanan bir HTML gövdesi üret (sadece <body> içeriği, \
  <html>/<head> etiketi ekleme).
- En üstte "Öne Çıkanlar" bölümünde, kanun, cumhurbaşkanlığı kararnamesi, önemli \
  yönetmelik/tebliğ değişiklikleri gibi gerçekten önemli olabilecek 3-8 maddeyi listele, \
  her biri için başlığa dayanarak 1 cümlelik anlaşılır Türkçe açıklama yaz.
- Altında kategori başlıklarına göre gruplanmış tam listeyi ver (madde başlığı + link), \
  kısa tutmak için tebliğ/ilan gibi çok sayıda benzer maddeyi tek satırda özetleyebilirsin.
- Eğer madde bulunamadıysa bunu açıkça belirt ve kaynak sayfaya link ver: {day.source_url}
- Yalnızca başlıklardan yola çıkarak makul çıkarımlar yap, uydurma bilgi verme; emin \
  olmadığın konularda "resmi metne bakılmalı" gibi ifadeler kullan.
- Türkçe yaz.

Kaynak: {day.source_url}

Ham liste:
{payload}
"""

    response = client.messages.create(
        model=model,
        max_tokens=4000,
        messages=[{"role": "user", "content": prompt}],
    )
    html_body = "".join(
        block.text for block in response.content if block.type == "text"
    ).strip()

    subject = f"Resmi Gazete Özeti - {day.date}"
    return subject, html_body


def send_email(subject: str, html_body: str) -> None:
    to_email = os.environ["TO_EMAIL"]
    from_email = os.environ["FROM_EMAIL"]
    api_key = os.environ["RESEND_API_KEY"]

    resp = requests.post(
        "https://api.resend.com/emails",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "from": from_email,
            "to": [to_email],
            "subject": subject,
            "html": html_body,
        },
        timeout=30,
    )
    if resp.status_code >= 300:
        raise RuntimeError(
            f"Resend API error {resp.status_code}: {resp.text}"
        )


def main() -> int:
    tz = ZoneInfo("Europe/Istanbul")
    date_override = os.environ.get("GAZETTE_DATE")
    target_date = (
        datetime.strptime(date_override, "%Y-%m-%d").replace(tzinfo=tz)
        if date_override
        else datetime.now(tz)
    )
    date_str = target_date.strftime("%d.%m.%Y")
    source_url = gazette_url_for(target_date)

    print(f"Fetching {source_url}", file=sys.stderr)
    resp = fetch_page(source_url)

    model = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-5")

    if resp.status_code == 404:
        day = GazetteDay(date=date_str, source_url=source_url)
    else:
        resp.raise_for_status()
        day = parse_gazette(resp.text, source_url, date_str)

    print(f"Parsed {day.item_count} items across {len(day.categories)} categories",
          file=sys.stderr)

    # Debug artifact so a bad parse is easy to diagnose from the workflow run.
    with open("gazette_items.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                "date": day.date,
                "source_url": day.source_url,
                "categories": {
                    cat: [item.__dict__ for item in items]
                    for cat, items in day.categories.items()
                },
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    subject, html_body = build_email_html(day, model)
    send_email(subject, html_body)
    print("Email sent.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
